import Layout from "@/components/Common/Layout";
import Navbar from "@/components/Common/Navbar";
import TableHeader from "@/components/Common/TableHeader";
import ProductTable from "@/components/ProductTable";

const products = [
  {
    item_code: "ABC123",
    name: "Item 1",
    description: "Description for Item 1",
    sale_price: 19.99,
    stock_quantity: 5,
    unit: "pieces",
    stock_thresh_hold_value: 10,
    returnable: true,
    created_by: "user_id_1",
    created_at: "Dec 2, 2023",
    updated_at: "Dec 2, 2023",
  },
  {
    item_code: "DEF456",
    name: "Item 2",
    description: "Description for Item 2",
    sale_price: 29.99,
    stock_quantity: 50,
    unit: "packs",
    stock_thresh_hold_value: 5,
    returnable: false,
    created_by: "user_id_2",
    created_at: "Dec 2, 2023",
    updated_at: "Dec 2, 2023",
  },
  {
    item_code: "ABC123",
    name: "Item 1",
    description: "Description for Item 1",
    sale_price: 19.99,
    stock_quantity: 100,
    unit: "pieces",
    stock_thresh_hold_value: 10,
    returnable: true,
    created_by: "user_id_1",
    created_at: "Dec 2, 2023",
    updated_at: "Dec 2, 2023",
  },
  {
    item_code: "DEF456",
    name: "Item 2",
    description: "Description for Item 2",
    sale_price: 29.99,
    stock_quantity: 50,
    unit: "packs",
    stock_thresh_hold_value: 5,
    returnable: false,
    created_by: "user_id_2",
    created_at: "Dec 2, 2023",
    updated_at: "Dec 2, 2023",
  },
  {
    item_code: "ABC123",
    name: "Item 1",
    description: "Description for Item 1",
    sale_price: 19.99,
    stock_quantity: 100,
    unit: "pieces",
    stock_thresh_hold_value: 10,
    returnable: true,
    created_by: "user_id_1",
    created_at: "Dec 2, 2023",
    updated_at: "Dec 2, 2023",
  },
  {
    item_code: "DEF456",
    name: "Item 2",
    description: "Description for Item 2",
    sale_price: 29.99,
    stock_quantity: 50,
    unit: "packs",
    stock_thresh_hold_value: 5,
    returnable: false,
    created_by: "user_id_2",
    created_at: "Dec 2, 2023",
    updated_at: "Dec 2, 2023",
  },
  {
    item_code: "ABC123",
    name: "Item 1",
    description: "Description for Item 1",
    sale_price: 19.99,
    stock_quantity: 100,
    unit: "pieces",
    stock_thresh_hold_value: 10,
    returnable: true,
    created_by: "user_id_1",
    created_at: "Dec 2, 2023",
    updated_at: "Dec 2, 2023",
  },
  {
    item_code: "DEF456",
    name: "Item 2",
    description: "Description for Item 2",
    sale_price: 29.99,
    stock_quantity: 50,
    unit: "packs",
    stock_thresh_hold_value: 5,
    returnable: false,
    created_by: "user_id_2",
    created_at: "Dec 2, 2023",
    updated_at: "Dec 2, 2023",
  },
  {
    item_code: "ABC123",
    name: "Item 1",
    description: "Description for Item 1",
    sale_price: 19.99,
    stock_quantity: 100,
    unit: "pieces",
    stock_thresh_hold_value: 10,
    returnable: true,
    created_by: "user_id_1",
    created_at: "Dec 2, 2023",
    updated_at: "Dec 2, 2023",
  },
  {
    item_code: "DEF456",
    name: "Item 2",
    description: "Description for Item 2",
    sale_price: 29.99,
    stock_quantity: 50,
    unit: "packs",
    stock_thresh_hold_value: 5,
    returnable: false,
    created_by: "user_id_2",
    created_at: "Dec 2, 2023",
    updated_at: "Dec 2, 2023",
  },
  {
    item_code: "ABC123",
    name: "Item 1",
    description: "Description for Item 1",
    sale_price: 19.99,
    stock_quantity: 100,
    unit: "pieces",
    stock_thresh_hold_value: 10,
    returnable: true,
    created_by: "user_id_1",
    created_at: "Dec 2, 2023",
    updated_at: "Dec 2, 2023",
  },
  {
    item_code: "DEF456",
    name: "Item 2",
    description: "Description for Item 2",
    sale_price: 29.99,
    stock_quantity: 50,
    unit: "packs",
    stock_thresh_hold_value: 5,
    returnable: false,
    created_by: "user_id_2",
    created_at: "Dec 2, 2023",
    updated_at: "Dec 2, 2023",
  },
];
export default function Product() {
  return (
    <Layout>
      <div className="w-[100%] p-10">
        <TableHeader
          tableHeader="Products"
          description="A list of all products including their information."
        />
        <ProductTable data={products} />
      </div>
    </Layout>
  );
}
